Repository RiccardoElena/UninaDelivery, pull requests merged in 2023-11, with the labels that each got.

#1 test: removed useless test directory
  test/Starter.java
  test/package-info.java
Labels: test

#5 fix: checked action errors
  README.md
Labels: fix

#8 fix: Updated contributors number
  README.md
Labels: fix

#9 chore: updating testing branch to master
  .all-contributorsrc
  README.md
Labels: chore

#10 chore: added ignored files list and removed ignored files
  .gitignore
  .vscode/extension.json
  .vscode/ltex.dictionary.it.txt
  .vscode/settings.json
Labels: chore
